name: smarthome
description: "Smart Home  - Internet of Things"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.6

  # https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^5.9.0

  # https://pub.dev/packages/get
  get: ^4.6.6

  # https://pub.dev/packages/get_it
  get_it: ^7.2.0

  # https://pub.dev/packages/flutter_easyloading
  flutter_easyloading: ^3.0.5

  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.10+1

  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.3.1

  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.2.5

  # https://pub.dev/packages/share_plus
  share_plus: ^7.2.2

  # https://pub.dev/packages/scroll_to_index
  scroll_to_index: ^3.0.1

  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.2.2

  # https://pub.dev/packages/dio
  dio: ^5.0.2

  # https://pub.dev/packages/file_picker
  file_picker: ^6.1.1
  # https://pub.dev/packages/speech_to_text
  speech_to_text: ^6.6.1

  #https://pub.dev/packages/loading_animation_widget
  loading_animation_widget: ^1.2.1

  #https://pub.dev/packages/flex_color_picker
  flex_color_picker: ^3.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/base/images/logo_app.png"

flutter:
  uses-material-design: true

  assets:
    - assets/base/
    - assets/base/icons/
    - assets/base/images/
    - assets/base/flags/
    - assets/base/boarding/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/base/fonts/roboto/RobotoCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/base/fonts/roboto/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/base/fonts/roboto/RobotoCondensed-SemiBold.ttf
          weight: 800
